/* Automatically generated by Ferrum HDL. */

// src/lib.rs: 7
module top
(
    // Inputs
    input wire clk,
    input wire rst,
    // Outputs
    output reg [2:0] _reg
);

    initial begin
        _reg = 3'd0;
    end
    always @(posedge clk) begin
        if (rst)
            _reg <= 3'd0;
        else
            _reg <= comb;
    end

    wire [2:0] _$1;
    assign _$1 = 1;
    wire [2:0] comb;
    assign comb = _reg + _$1;

endmodule

